### ISSUE TITLE
Add support for `pack download-sbom`

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/occam#125]
## Summary
The `pack` CLI supports a new command, `download-sbom`, that allows users to download the launch SBOM from a container image. We should include this in `occam` so that we can leverage it in our testing processes.

PR: https://github.com/buildpacks/pack/pull/1351

**Comment by fg-j** [comment]
It seems like `pack build --sbom-output-dir` dumps the build, launch, and cache SBOMs into the specified output directory. This means there will be a way to access launch SBOM for a build once completing #126. Is supporting this separate command still worth doing?

**Comment by ryanmoran** [comment]
@fg-j If that's the case, then it makes sense to hold off on this until we have a situation that would require it.
