### ISSUE TITLE
Adding helper for containerstructure tests

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/occam#146]
Currently `occam` offers helper for `pack` and `docker`. It might be quite useful to offer something similar for `containerstructure tests`.

see https://github.com/GoogleContainerTools/container-structure-test

With this `containerstructure tests`, it would be easy to check just built images.

e.g.:

```go
cst = NewContainerStructureTest().WithVerbose()
logs, err := cst.Run.Execute("test/my-image", "tests.yaml")
```

**Comment by robdimsdale** [comment]
I think this is a sensible addition to this project. @c0d1ngm0nk3y (maybe also @garethjevans?) are you willing to create a PR?
