### ISSUE TITLE
Adding helper for test containers

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/occam#147]
Currently `occam` offers helper for `pack` and `docker`. It might be quite useful to offer something similar for `test containers`.

see https://github.com/testcontainers/testcontainers-go

With this `test containers`, it would be easy to test just built images.

e.g.:

```go
tc = NewTestContainers().WithEnv(map[string]string{})
logs, err := tc.Run.Execute("test/my-image")
```

**Comment by fg-j** [comment]
Hey @c0d1ngm0nk3y. Thanks for the suggestion. I'm curious - is there a reason you'd prefer to use a wrapper/helper as opposed to using `testcontainers-go` library directly?

**Comment by robdimsdale** [comment]
I think this is a sensible addition to this project. @c0d1ngm0nk3y @garethjevans are you willing to create a PR?
