### ISSUE TITLE
Release with latest changes

### ISSUE THREAD

**Issue by pacostas** [paketo-buildpacks/occam#236]
## Release
Is it possible to create a release that will include the latest changes,  as I would like to use the .WithExtension option in the integration tests https://github.com/paketo-community/ubi-nodejs-extension/pull/9

**Comment by robdimsdale** [comment]
Sorry, we don't have a good process for releasing this library regularly.

I just released it: https://github.com/paketo-buildpacks/occam/releases/tag/v0.17.0
