### ISSUE TITLE
WithRegistry on pack

### ISSUE THREAD

**Issue by mhdawson** [paketo-buildpacks/occam#245]
## Describe the Enhancement
When running integration tests and using extensions (for example - https://github.com/paketo-community/ubi-nodejs-extension) builders must be run from a registry.  This means that once a builder has been built by occam we need it to push it to the registry and then later run the container from that registry.

The scripts which run the tests can handle start/stopping the registry.

I think what's need is a `WithRegistry` that could be used something like

``` go
 _, logs, err = pack.WithNoColor().Build.
                                WithPullPolicy("never").
                                WithExtensions(
                                        settings.Buildpacks.NodeExtension.Online,
                                ).
                                WithBuildpacks(
                                        settings.Buildpacks.NodeEngine.Online,
                                        settings.Buildpacks.BuildPlan.Online,
                                ).
                                WithEnv(map[string]string{"BP_NODE_VERSION": "~14"}).
                                WithSBOMOutputDir(sbomDir).
                                WithNetwork("host").
                                WithRegistry("localhost:5000"),
                                WithPullPolicy("always").
                                Execute(name, source)
```

## Possible Solution
Add `WithRegistry` as described above.

If its passed an empty string, it has no effect. This will let it be used in all integration tests but only have effect if a registry must be used.

If it is passed a string, once built a container is pushed to the registry and all later use of that container uses the version pushed to the registry.

**Comment by mhdawson** [comment]
If that sounds like it's the right way to go. @pacostas or myself can work on a PR to add that.

**Comment by mhdawson** [comment]
@sophiewigmore does what I've proposed sound reasonable to you?

**Comment by robdimsdale** [comment]
This sounds reasonable to me. For now we can just add `WithRegistry` and not handle the startup/teardown of the registry.

Longer-term I'd like to explore moving that logic into occam too. We are also using a registry in the arm64 stacks tests (which don't use `pack build` and hence aren't impacted by this specific change) and I'd like to find a way to commonize the registry handling logic rather than re-inventing this multiple times. I think that's out of scope of this PR, though.

**Comment by mhdawson** [comment]
We currently think this is not needed after all.  The integration tests for ubi-nodejs-extension use the buildpackless builder which is already published to a registry and extends it by adding buildpacks and extensions. I had thought it would be creating a new builder which is not the case.

This PR moves the ubi-nodejs-extension to the latest pack and lifecycle levels and from @pacostas's testing the integration tests still run/pass. - https://github.com/paketo-community/ubi-nodejs-extension/pull/18

I'll close this issue after that PR lands.

**Comment by robdimsdale** [comment]
Alright - thanks for the heads-up. No code is always better than new code, so I'm supportive of not adding a feature we don't need!

**Comment by mhdawson** [comment]
closing
