### ISSUE TITLE
Add an informative README

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/occam#83]
## What happened?

* What were you attempting to do?
Understand what this library does

* What did you expect to happen?
I was hoping the README would tell me.

* What was the actual behavior? Please provide log output, if possible.
No README :(

**Comment by sophiewigmore** [comment]
Since #122 was merged, we should ensure that the README created in this issue includes a link to the GoDoc site like we have in [packit](https://github.com/paketo-buildpacks/packit/blob/v2/README.md?plain=1#L1-L3)

**Comment by sophiewigmore** [comment]
Related PR: https://github.com/paketo-buildpacks/occam/pull/145

**Comment by ryanmoran** [comment]
Is this resolved since  #145 was merged?
